# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvis2.0.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import webbrowser


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1592, 927)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spekerauto = QtWidgets.QLabel(self.centralwidget)
        self.spekerauto.setGeometry(QtCore.QRect(-150, -30, 1741, 961))
        self.spekerauto.setText("")
        self.spekerauto.setPixmap(QtGui.QPixmap("../../JARVIS2.0/autoplay.png"))
        self.spekerauto.setObjectName("spekerauto")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(730, 380, 171, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../JARVIS2.0/spek2.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.Ginfo = QtWidgets.QLabel(self.centralwidget)
        self.Ginfo.setGeometry(QtCore.QRect(1020, 580, 61, 61))
        self.Ginfo.setText("")
        self.Ginfo.setObjectName("Ginfo")
        self.speker = QtWidgets.QLabel(self.centralwidget)
        self.speker.setGeometry(QtCore.QRect(720, 380, 191, 151))
        self.speker.setText("")
        self.speker.setPixmap(QtGui.QPixmap("../Users/bhoir/OneDrive/Documents/Pictures/Saved Pictures/spek2.gif"))
        self.speker.setScaledContents(True)
        self.speker.setObjectName("speker")
        self.Ginfo_2 = QtWidgets.QLabel(self.centralwidget)
        self.Ginfo_2.setGeometry(QtCore.QRect(1020, 580, 61, 61))
        self.Ginfo_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ginfo_2.setStyleSheet("background-color: transparent;\n"
        "color:aqua;")
        self.Ginfo_2.setText("")
        self.Ginfo_2.setObjectName("Ginfo_2")
        self.news = QtWidgets.QLabel(self.centralwidget)
        self.news.setGeometry(QtCore.QRect(1070, 470, 41, 81))
        self.news.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.news.setStyleSheet("background-color:transparent;\n"
"")
        self.news.setText("")
        self.news.setObjectName("news")
        self.alarm = QtWidgets.QLabel(self.centralwidget)
        self.alarm.setGeometry(QtCore.QRect(1070, 350, 41, 91))
        self.alarm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alarm.setStyleSheet("background-color:transparent;\n"
"")
        self.alarm.setText("")
        self.alarm.setObjectName("alarm")
        self.music = QtWidgets.QLabel(self.centralwidget)
        self.music.setGeometry(QtCore.QRect(1020, 260, 61, 71))
        self.music.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.music.setStyleSheet("background-color:transparent;\n"
"")
        self.music.setText("")
        self.music.setObjectName("music")
        self.setting = QtWidgets.QLabel(self.centralwidget)
        self.setting.setGeometry(QtCore.QRect(820, 150, 91, 41))
        self.setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting.setStyleSheet("background-color:transparent;\n"
"")
        self.setting.setText("")
        self.setting.setObjectName("setting")
        self.email = QtWidgets.QLabel(self.centralwidget)
        self.email.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.email.setGeometry(QtCore.QRect(710, 150, 91, 41))
        self.email.setStyleSheet("background-color:transparent;\n"
"")
        self.email.setText("")
        self.email.setObjectName("email")
        self.startbut = QtWidgets.QLabel(self.centralwidget)
        self.startbut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startbut.setGeometry(QtCore.QRect(710, 770, 101, 41))
        self.startbut.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color: rgb(47, 255, 255);\n"
"border:1px solid aqua;\n"
"border-radius:10px;")
        self.startbut.setObjectName("startbut")
        self.quitbut = QtWidgets.QLabel(self.centralwidget)
        self.quitbut.setGeometry(QtCore.QRect(820, 770, 101, 41))
        self.quitbut.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quitbut.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color:red;\n"
"border:1px solid red;\n"
"border-radius:10px;")
        self.quitbut.setObjectName("quitbut")
        self.whats = QtWidgets.QLabel(self.centralwidget)
        self.whats.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.whats.setGeometry(QtCore.QRect(1380, 200, 171, 61))
        self.whats.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color: rgb(47, 255, 255);\n"
"border:1px solid aqua;\n"
"border-radius:10px;")
        self.whats.setObjectName("whats")
        self.youtube = QtWidgets.QLabel(self.centralwidget)
        self.youtube.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.youtube.setGeometry(QtCore.QRect(1380, 370, 171, 61))
        self.youtube.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color: rgb(47, 255, 255);\n"
"border:1px solid aqua;\n"
"border-radius:10px;")
        self.youtube.setObjectName("youtube")
        self.github = QtWidgets.QLabel(self.centralwidget)
        self.github.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.github.setGeometry(QtCore.QRect(1380, 540, 171, 61))
        self.github.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color: rgb(47, 255, 255);\n"
"border:1px solid aqua;\n"
"border-radius:10px;")
        self.github.setObjectName("github")
        self.linkedin = QtWidgets.QLabel(self.centralwidget)
        self.linkedin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.linkedin.setGeometry(QtCore.QRect(1380, 710, 171, 61))
        self.linkedin.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color: rgb(47, 255, 255);\n"
"border:1px solid aqua;\n"
"border-radius:10px;")
        self.linkedin.setObjectName("linkedin")
        self.vscode = QtWidgets.QLabel(self.centralwidget)
        self.vscode.setGeometry(QtCore.QRect(50, 790, 171, 61))
        self.vscode.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vscode.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color: rgb(47, 255, 255);\n"
"border:1px solid aqua;\n"
"border-radius:10px;")
        self.vscode.setObjectName("vscode")
        self.notepad = QtWidgets.QLabel(self.centralwidget)
        self.notepad.setGeometry(QtCore.QRect(50, 650, 171, 61))
        self.notepad.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notepad.setStyleSheet("\n"
"font: 14pt \"Segoe Fluent Icons\";\n"
"color: rgb(47, 255, 255);\n"
"border:1px solid aqua;\n"
"border-radius:10px;")
        self.notepad.setObjectName("notepad")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startbut.setText(_translate("MainWindow", "  START"))
        self.quitbut.setText(_translate("MainWindow", "   QUIT"))
        self.whats.setText(_translate("MainWindow", "    Whatsapp"))
        self.youtube.setText(_translate("MainWindow", "    YouTube"))
        self.github.setText(_translate("MainWindow", "     GitHub"))
        self.linkedin.setText(_translate("MainWindow", "    LinkedIn"))
        self.vscode.setText(_translate("MainWindow", "     VS-CODE"))
        self.notepad.setText(_translate("MainWindow", "    NotePad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
